### ISSUE TITLE
PrintTwoSideCard

### ISSUE THREAD

**Issue by enricodeveloper** [jarretth/zebra#1]
Hello,
it's possible to have an example in c # ?, I need to print two images on front and back, but I don't know how to do it.

Thank you

**Comment by jarretth** [comment]
Sorry, I don't have any C# Examples - this is a Golang library, but the usage maps pretty closely to the DLL calls you would make in C#: 
1. ZBRGDIInitGraphics
2. //ZBRGDIDrawTextUnicode etc
3. ZBRGDIPrintGraphics
4. ZBRGDIClearGraphics
5. //ZBRGDIDrawTextUnicode etc
6. ZBRGDIPrintGraphics
7. ZBRGDIClearGraphics
8. ZBRGDIIsPrinterReady loop
9. ZBRGDICloseGraphics

If the printer supports two-sided printing, I believe printing/clearing the graphics handle switches sides. Closing the graphics handle finishes the card and spits it out. I don't have one of these to test with anymore, so unfortunately I can't help more than that!
